[[override]]
  name = "k8s.io/api"
  version = "kubernetes-1.10.1"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.10.1"

[[override]]
  name = "k8s.io/apiextensions-apiserver"
  version = "kubernetes-1.10.1"

[[override]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.10.1"
