// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/


// Code generated by D:\github\go\bin\deepcopy-gen.exe. DO NOT EDIT.

package v1

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EsOperator) DeepCopyInto(out *EsOperator) {
*out = *in
out.TypeMeta = in.TypeMeta
in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
in.Spec.DeepCopyInto(&out.Spec)
return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EsOperator.
func (in *EsOperator) DeepCopy() *EsOperator {
if in == nil { return nil }
out := new(EsOperator)
in.DeepCopyInto(out)
return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EsOperatorList) DeepCopyInto(out *EsOperatorList) {
*out = *in
out.TypeMeta = in.TypeMeta
out.ListMeta = in.ListMeta
if in.Items != nil {
in, out := &in.Items, &out.Items
*out = make([]EsOperator, len(*in))
for i := range *in {
(*in)[i].DeepCopyInto(&(*out)[i])
}
}
return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EsOperatorList.
func (in *EsOperatorList) DeepCopy() *EsOperatorList {
if in == nil { return nil }
out := new(EsOperatorList)
in.DeepCopyInto(out)
return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EsOperatorSpec) DeepCopyInto(out *EsOperatorSpec) {
*out = *in
if in.SomeValue != nil {
in, out := &in.SomeValue, &out.SomeValue
*out = new(int32)
**out = **in}
return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EsOperatorSpec.
func (in *EsOperatorSpec) DeepCopy() *EsOperatorSpec {
if in == nil { return nil }
out := new(EsOperatorSpec)
in.DeepCopyInto(out)
return out
}

