apiVersion: v1
kind: Service
metadata:
  name: test-1
  namespace: default
  labels:
    k8s-app: elasticsearch-logging
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
    kubernetes.io/name: "Elasticsearch"
spec:
  ports:
  - port: 9200
    name: elasticsearch-db
    protocol: TCP
    targetPort: db
  - port: 9300
    name: elasticsearch-transport
    protocol: TCP
    targetPort: transport
  selector:
    app: elastic-search
    controller: test
    deploy-index: test-1

