apiVersion: v1
kind: ServiceAccount
metadata:
  name: es-operator
  namespace: operator

---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: es-operator
rules:
- apiGroups:
  - augusto.cn
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - "*"
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - "*"

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: es-operator
subjects:
- kind: ServiceAccount
  name: es-operator
  namespace: operator
roleRef:
  kind: ClusterRole
  name: es-operator
  apiGroup: rbac.authorization.k8s.io

--- 


