/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	augustocnv1 "github.com/staugust/esoperator/pkg/apis/augusto.cn/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeEsClusterLists implements EsClusterListInterface
type FakeEsClusterLists struct {
	Fake *FakeAugustoV1
	ns   string
}

var esclusterlistsResource = schema.GroupVersionResource{Group: "augusto.cn", Version: "v1", Resource: "esclusterlists"}

var esclusterlistsKind = schema.GroupVersionKind{Group: "augusto.cn", Version: "v1", Kind: "EsClusterList"}

// Get takes name of the esClusterList, and returns the corresponding esClusterList object, and an error if there is any.
func (c *FakeEsClusterLists) Get(name string, options v1.GetOptions) (result *augustocnv1.EsClusterList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(esclusterlistsResource, c.ns, name), &augustocnv1.EsClusterList{})

	if obj == nil {
		return nil, err
	}
	return obj.(*augustocnv1.EsClusterList), err
}

// List takes label and field selectors, and returns the list of EsClusterLists that match those selectors.
func (c *FakeEsClusterLists) List(opts v1.ListOptions) (result *augustocnv1.EsClusterListList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(esclusterlistsResource, esclusterlistsKind, c.ns, opts), &augustocnv1.EsClusterListList{})

	if obj == nil {
		return nil, err
	}
	return obj.(*augustocnv1.EsClusterListList), err
}

// Watch returns a watch.Interface that watches the requested esClusterLists.
func (c *FakeEsClusterLists) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(esclusterlistsResource, c.ns, opts))

}

// Create takes the representation of a esClusterList and creates it.  Returns the server's representation of the esClusterList, and an error, if there is any.
func (c *FakeEsClusterLists) Create(esClusterList *augustocnv1.EsClusterList) (result *augustocnv1.EsClusterList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(esclusterlistsResource, c.ns, esClusterList), &augustocnv1.EsClusterList{})

	if obj == nil {
		return nil, err
	}
	return obj.(*augustocnv1.EsClusterList), err
}

// Update takes the representation of a esClusterList and updates it. Returns the server's representation of the esClusterList, and an error, if there is any.
func (c *FakeEsClusterLists) Update(esClusterList *augustocnv1.EsClusterList) (result *augustocnv1.EsClusterList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(esclusterlistsResource, c.ns, esClusterList), &augustocnv1.EsClusterList{})

	if obj == nil {
		return nil, err
	}
	return obj.(*augustocnv1.EsClusterList), err
}

// Delete takes name of the esClusterList and deletes it. Returns an error if one occurs.
func (c *FakeEsClusterLists) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(esclusterlistsResource, c.ns, name), &augustocnv1.EsClusterList{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeEsClusterLists) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(esclusterlistsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &augustocnv1.EsClusterListList{})
	return err
}

// Patch applies the patch and returns the patched esClusterList.
func (c *FakeEsClusterLists) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *augustocnv1.EsClusterList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(esclusterlistsResource, c.ns, name, data, subresources...), &augustocnv1.EsClusterList{})

	if obj == nil {
		return nil, err
	}
	return obj.(*augustocnv1.EsClusterList), err
}
