/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	augusto_cn_v1 "github.com/staugust/esoperator/pkg/apis/augusto.cn/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeEsClusters implements EsClusterInterface
type FakeEsClusters struct {
	Fake *FakeAugustoV1
	ns   string
}

var esclustersResource = schema.GroupVersionResource{Group: "augusto.cn", Version: "v1", Resource: "esclusters"}

var esclustersKind = schema.GroupVersionKind{Group: "augusto.cn", Version: "v1", Kind: "EsCluster"}

// Get takes name of the esCluster, and returns the corresponding esCluster object, and an error if there is any.
func (c *FakeEsClusters) Get(name string, options v1.GetOptions) (result *augusto_cn_v1.EsCluster, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(esclustersResource, c.ns, name), &augusto_cn_v1.EsCluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*augusto_cn_v1.EsCluster), err
}

// List takes label and field selectors, and returns the list of EsClusters that match those selectors.
func (c *FakeEsClusters) List(opts v1.ListOptions) (result *augusto_cn_v1.EsClusterList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(esclustersResource, esclustersKind, c.ns, opts), &augusto_cn_v1.EsClusterList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &augusto_cn_v1.EsClusterList{ListMeta: obj.(*augusto_cn_v1.EsClusterList).ListMeta}
	for _, item := range obj.(*augusto_cn_v1.EsClusterList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested esClusters.
func (c *FakeEsClusters) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(esclustersResource, c.ns, opts))

}

// Create takes the representation of a esCluster and creates it.  Returns the server's representation of the esCluster, and an error, if there is any.
func (c *FakeEsClusters) Create(esCluster *augusto_cn_v1.EsCluster) (result *augusto_cn_v1.EsCluster, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(esclustersResource, c.ns, esCluster), &augusto_cn_v1.EsCluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*augusto_cn_v1.EsCluster), err
}

// Update takes the representation of a esCluster and updates it. Returns the server's representation of the esCluster, and an error, if there is any.
func (c *FakeEsClusters) Update(esCluster *augusto_cn_v1.EsCluster) (result *augusto_cn_v1.EsCluster, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(esclustersResource, c.ns, esCluster), &augusto_cn_v1.EsCluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*augusto_cn_v1.EsCluster), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeEsClusters) UpdateStatus(esCluster *augusto_cn_v1.EsCluster) (*augusto_cn_v1.EsCluster, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(esclustersResource, "status", c.ns, esCluster), &augusto_cn_v1.EsCluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*augusto_cn_v1.EsCluster), err
}

// Delete takes name of the esCluster and deletes it. Returns an error if one occurs.
func (c *FakeEsClusters) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(esclustersResource, c.ns, name), &augusto_cn_v1.EsCluster{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeEsClusters) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(esclustersResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &augusto_cn_v1.EsClusterList{})
	return err
}

// Patch applies the patch and returns the patched esCluster.
func (c *FakeEsClusters) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *augusto_cn_v1.EsCluster, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(esclustersResource, c.ns, name, data, subresources...), &augusto_cn_v1.EsCluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*augusto_cn_v1.EsCluster), err
}
