/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	time "time"

	augusto_cn_v1 "github.com/staugust/esoperator/pkg/apis/augusto.cn/v1"
	versioned "github.com/staugust/esoperator/pkg/client/clientset/versioned"
	internalinterfaces "github.com/staugust/esoperator/pkg/client/informers/externalversions/internalinterfaces"
	v1 "github.com/staugust/esoperator/pkg/client/listers/augusto.cn/v1"
	meta_v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// EsClusterInformer provides access to a shared informer and lister for
// EsClusters.
type EsClusterInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.EsClusterLister
}

type esClusterInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewEsClusterInformer constructs a new informer for EsCluster type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewEsClusterInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredEsClusterInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredEsClusterInformer constructs a new informer for EsCluster type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredEsClusterInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options meta_v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.AugustoV1().EsClusters(namespace).List(options)
			},
			WatchFunc: func(options meta_v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.AugustoV1().EsClusters(namespace).Watch(options)
			},
		},
		&augusto_cn_v1.EsCluster{},
		resyncPeriod,
		indexers,
	)
}

func (f *esClusterInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredEsClusterInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *esClusterInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&augusto_cn_v1.EsCluster{}, f.defaultInformer)
}

func (f *esClusterInformer) Lister() v1.EsClusterLister {
	return v1.NewEsClusterLister(f.Informer().GetIndexer())
}
