/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/staugust/esoperator/pkg/apis/augusto.cn/v1"
	scheme "github.com/staugust/esoperator/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// EsClustersGetter has a method to return a EsClusterInterface.
// A group's client should implement this interface.
type EsClustersGetter interface {
	EsClusters(namespace string) EsClusterInterface
}

// EsClusterInterface has methods to work with EsCluster resources.
type EsClusterInterface interface {
	Create(*v1.EsCluster) (*v1.EsCluster, error)
	Update(*v1.EsCluster) (*v1.EsCluster, error)
	UpdateStatus(*v1.EsCluster) (*v1.EsCluster, error)
	Delete(name string, options *metav1.DeleteOptions) error
	DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error
	Get(name string, options metav1.GetOptions) (*v1.EsCluster, error)
	List(opts metav1.ListOptions) (*v1.EsClusterList, error)
	Watch(opts metav1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.EsCluster, err error)
	EsClusterExpansion
}

// esClusters implements EsClusterInterface
type esClusters struct {
	client rest.Interface
	ns     string
}

// newEsClusters returns a EsClusters
func newEsClusters(c *AugustoV1Client, namespace string) *esClusters {
	return &esClusters{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the esCluster, and returns the corresponding esCluster object, and an error if there is any.
func (c *esClusters) Get(name string, options metav1.GetOptions) (result *v1.EsCluster, err error) {
	result = &v1.EsCluster{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("esclusters").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of EsClusters that match those selectors.
func (c *esClusters) List(opts metav1.ListOptions) (result *v1.EsClusterList, err error) {
	result = &v1.EsClusterList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("esclusters").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested esClusters.
func (c *esClusters) Watch(opts metav1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("esclusters").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a esCluster and creates it.  Returns the server's representation of the esCluster, and an error, if there is any.
func (c *esClusters) Create(esCluster *v1.EsCluster) (result *v1.EsCluster, err error) {
	result = &v1.EsCluster{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("esclusters").
		Body(esCluster).
		Do().
		Into(result)
	return
}

// Update takes the representation of a esCluster and updates it. Returns the server's representation of the esCluster, and an error, if there is any.
func (c *esClusters) Update(esCluster *v1.EsCluster) (result *v1.EsCluster, err error) {
	result = &v1.EsCluster{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("esclusters").
		Name(esCluster.Name).
		Body(esCluster).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *esClusters) UpdateStatus(esCluster *v1.EsCluster) (result *v1.EsCluster, err error) {
	result = &v1.EsCluster{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("esclusters").
		Name(esCluster.Name).
		SubResource("status").
		Body(esCluster).
		Do().
		Into(result)
	return
}

// Delete takes name of the esCluster and deletes it. Returns an error if one occurs.
func (c *esClusters) Delete(name string, options *metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("esclusters").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *esClusters) DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("esclusters").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched esCluster.
func (c *esClusters) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.EsCluster, err error) {
	result = &v1.EsCluster{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("esclusters").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
